- name: "install docker"
  apt:
    name: docker.io
    state: present
    update_cache: yes
  tags: docker

- name: "enable and start docker service"
  service:
    name: docker
    enabled: yes
    state: started
  tags: docker

# - name: install python + pip
#   apt:
#     name: "{{ item }}"
#     state: present
#     update_cache: yes
#   loop:
#     - python3
#     - python3-pip
#   tags: docker

- name: install docker sdk for python
  apt:
    name: python3-docker
    state: present
    update_cache: yes
  tags: docker

- name: "diploy docker container"
  import_tasks: deploy_docker.yml
  tags: docker
  