
common_packages:
  - git
  - curl
  - unzip

docker_image_name: "ogshabzy23101/phone-e-commerce"
docker_image_tag: "latest"
docker_container_name: "myapp_container"
docker_container_port: 80
host_port: 80